In [ ]:
import datetime

current_time = datetime.datetime.now().time()  # breaks the program if wrong trading time -------------------------------.                        |
if current_time >= datetime.time(23) or current_time < datetime.time(1, 30):
    print('yes')

In [ ]:
import pywhatkit

phone_number = "+2347048275297"  # Replace with the recipient's number with country code
message = "This is a message sent using PyWhatKit."

# Send the message immediately
pywhatkit.sendwhatmsg_instantly(phone_number, message, tab_close=True, close_time=3)

# # Or, schedule the message for a specific time (hour, minute)
# pywhatkit.sendwhatmsg(phone_number, message, 6, 51)  # Send at 2:30 PM

In [98]:
# import pywhatkit

# # Variables
# phone_numer = '+2347048275297'
# group_id = ''
# message = 'Write the message here'
# time_hour = 14
# time_minute = 50
# waiting_time_to_send = 15
# close_tab = True
# waiting_time_to_close = 2

# mode = "contact"

# if mode == "contact":
#     # Send a WhastApp message to an specific contact
#     pywhatkit.sendwhatmsg_instantly(phone_numer, message, time_hour, time_minute, waiting_time_to_send, close_tab, waiting_time_to_close)
# elif mode == "group":
#     # Send a WhastApp message to an specific group
#     pywhatkit.sendwhatmsg_to_group(group_id, message, time_hour, time_minute, waiting_time_to_send, close_tab, waiting_time_to_close)
# else:
#     print("Error code: 97654")
#     print("Error Message: Please select a mode to send your message.")

In [78]:
import pandas as pd

ball_colors = ("red", "green", "blue")

# n1, n2, n3, n4, n5 = map(int, "41042")  # 22432  32231
# data_list = [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
# data_list = [110, 111]
# data_list = [2, 9, 12, 25, 30, 41, 56, 62, 73, 84, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114]
# data_list = [1, 2, 3, 4, 5, 6]
# data_list = [1, 3, 4, 5, 6, 7, 8, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29,
#             31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 
#             60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 83, 85, 86, 87]
# data_list = [2, 9, 12, 25, 30, 41, 56, 62, 73]
# data_list = [113, 114]
# data_list = [115, 116]
# data_list = [113, 114, 115, 116]
data_list = [111, 112, 113, 114, 115, 116, 117, 118]
data_list = [119, 120, 121, 122, 123]
# data_list = [
#     1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
#     31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 
#     60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
#     90, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109
# ]
# data_list = [80, 81, 82, 83, 84, 85, 86, 87, 90, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 111, 112]
total_wins = 0
total_loss = 0
main_counter = 0

for x in data_list:
    # print(f"--->>> Data - {x} <<<---")
    df = pd.read_csv(f"colour_records/rec_{x}_new.csv")
    # df = pd.read_csv(f"colour_records/new_00{x}.csv")
    # print(df.shape[0])

    record_check = []
    red_list, green_list, blue_list = [], [], []
    color_record = (red_list, green_list, blue_list)
    start_trade = False
    win_count = 0
    loss_count = 0

    counter = 0
    temp_check = []

    # for b1, b2, b3, b4, b5, b6 in zip(df["b1"], df["b2"], df["b3"], df["b4"], df["b5"], df["b6"]):
    for colours in df["colours"]:
        main_counter += 1
        numbers = [int(num) for num in (str(colours))]

        if len(numbers) == 1:
            numbers.insert(0, 0)
            numbers.insert(0, 0)
    
        elif len(numbers) == 2:
            numbers.insert(0, 0)
        record_check.append(numbers)

        # red, green, blue = numbers[0], numbers[1], numbers[2]
        red_list.append(numbers[0]), green_list.append(numbers[1]), blue_list.append(numbers[2])
        if len(record_check) >= 5:
            if start_trade == False:
                for pick in ["22442"]:  # "41042", "12424", "22442", "32231", "23432"
                    n1, n2, n3, n4, n5 = map(int, pick)  # 41042, 22432, 32231, 12424
                    if start_trade:
                        break
                    count = 0
                    for color in color_record:
                        if (color[-1] >= n1) and (color[-2] >= n2) and (color[-3] >= n3) and (color[-4] >= n4) and (color[-5] >= n5):
                            selected_color = ball_colors[count]
                            # print(f"{selected_color} - {color[-5:]} - {color[-5:-2]}")
                            start_trade = True
                            break
                        count += 1
            else:
                counter += 1 
                temp_check.append(color_record[count][-1])
                if counter == 3:
                    if any(x >= 2 for x in temp_check):
                        # print("-"*35, f"WIN", f"{selected_color} - {color_record[count][-3:]}")
                        win_count += 1
                    else:
                        # print("-"*100, f"Loss --> {selected_color} - {color_record[count][-3:]}")
                        loss_count += 1
                    start_trade = False
                    counter = 0
                    temp_check = []
                     
    total_wins += win_count
    total_loss += loss_count
    # print(f"Wins - {win_count} = {win_count * 5000}")
    # print(f"Loss - {loss_count} = {loss_count * 130000}")
    # print(f"---------------------------> Balance = {(win_count * 5000) - (loss_count * 130000)}\n")

print(f"\nTotal Wins = {total_wins}")
print(f"Total Loss = {total_loss}")

win_amount = total_wins * 5000
loss_amount = total_loss * 130000
print(f"Win Amount = {win_amount}")
print(f"Loss Amount = {loss_amount}")
print(f"\nBALANCE = {win_amount - loss_amount} <---")
print(f"\nTotal Draws = {main_counter} --> {round((main_counter * 50) / 60)} minutes --> {round(((main_counter * 50) / 60) / 60)} hours\
 --> {round((((main_counter * 50) / 60) / 60) / 10)} days")

Total Wins = 22
Total Loss = 1
Win Amount = 110000
Loss Amount = 130000

BALANCE = -20000 <---

Total Draws = 4530 --> 3775 minutes --> 63 hours --> 6 days

In [15]:
import pandas as pd

ball_colors = ("red", "green", "blue")

# n1, n2, n3, n4, n5, n6, n7, n8, n9, n10 = map(int, "4104254446")  # 22432  32231

# data_list = [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
# data_list = [110, 111]
data_list = [2, 9, 12, 25, 30, 41, 56, 62, 73, 84, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112]
# data_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
#                 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 
#                 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87]
total_wins = 0
total_loss = 0
main_counter = 0

for x in data_list:
    # print(f"--->>> Data - {x} <<<---")
    df = pd.read_csv(f"colour_records/rec_{x}_new.csv")
    # df = pd.read_csv(f"colour_records/new_00{x}.csv")
    # print(df.shape[0])

    record_check = []
    red_list, green_list, blue_list = [], [], []
    color_record = (red_list, green_list, blue_list)
    start_trade = False
    win_count = 0
    loss_count = 0

    counter = 0
    temp_check = []

    # for b1, b2, b3, b4, b5, b6 in zip(df["b1"], df["b2"], df["b3"], df["b4"], df["b5"], df["b6"]):
    for colours in df["colours"]:
        main_counter += 1
        numbers = [int(num) for num in (str(colours))]

        if len(numbers) == 1:
            numbers.insert(0, 0)
            numbers.insert(0, 0)
    
        elif len(numbers) == 2:
            numbers.insert(0, 0)
        record_check.append(numbers)

        # red, green, blue = numbers[0], numbers[1], numbers[2]
        red_list.append(numbers[0]), green_list.append(numbers[1]), blue_list.append(numbers[2])
        if len(record_check) >= 10:
            if start_trade == False:
                for pick in ["2244200000"]:  # "0042222121", "0042222021", "0042222020", "0042202031", "0110211342"
                    n1, n2, n3, n4, n5, n6, n7, n8, n9, n10 = map(int, pick)  # 41042, 22442, 32231, 12424
                    if start_trade:
                        break
                    count = 0
                    for color in color_record:
                        if (color[-1] >= n1) and (color[-2] >= n2) and (color[-3] >= n3) and (color[-4] >= n4) and (color[-5] >= n5) \
                        and (color[-6] >= n6) and (color[-7] >= n7) and (color[-8] >= n8) and (color[-9] >= n9) and (color[-10] >= n10):
                            selected_color = ball_colors[count]
                            # print(f"{selected_color} - {color[-5:]} - {color[-5:-2]}")
                            start_trade = True
                            break
                        count += 1
            else:
                counter += 1 
                temp_check.append(color_record[count][-1])
                if counter == 3:
                    if any(x >= 2 for x in temp_check):
                        # print("-"*35, f"WIN", f"{selected_color} - {color_record[count][-3:]}")
                        win_count += 1
                    else:
                        # print("-"*100, f"Loss --> {selected_color} - {color_record[count][-3:]}")
                        loss_count += 1
                    start_trade = False
                    counter = 0
                    temp_check = []
                     
    total_wins += win_count
    total_loss += loss_count
    # print(f"Wins - {win_count} = {win_count * 5000}")
    # print(f"Loss - {loss_count} = {loss_count * 130000}")
    # print(f"---------------------------> Balance = {(win_count * 5000) - (loss_count * 130000)}\n")

print(f"\nTotal Wins = {total_wins}")
print(f"Total Loss = {total_loss}")

win_amount = total_wins * 5000
loss_amount = total_loss * 130000
print(f"Win Amount = {win_amount}")
print(f"Loss Amount = {loss_amount}")
print(f"\nBALANCE = {win_amount - loss_amount} <---")
print(f"\nTotal Draws = {main_counter} --> {round((main_counter * 50) / 60)} minutes --> {round(((main_counter * 50) / 60) / 60)} hours\
 --> {round((((main_counter * 50) / 60) / 60) / 10)} days")

Total Wins = 140
Total Loss = 1
Win Amount = 700000
Loss Amount = 130000

BALANCE = 570000 <---

Total Draws = 34555 --> 28796 minutes --> 480 hours --> 48 days

In [ ]:
# 89.60 - "22442", "41042" ==== 1590000 - 5
# 87.16 - "12424", "41042" ==== 1835000 - 6
# 86.71 - "22442", "12424", "41042" ==== 2125000 - 7 ✔️
# 80.25 - "22442", "12424" ==== 1085000
# 79.66 - "22442", "12424", "41042", "23432" ==== 2415000 - 9
# 62.63 - "12424", "41042", "32432"

In [ ]:
import pandas as pd

ball_colors = ("red", "green", "blue")

# n1, n2, n3, n4, n5, n6, n7, n8, n9, n10 = map(int, "4104254446")  # 22432  32231

# data_list = [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
# data_list = [110, 111]
# data_list = [2, 9, 12, 25, 30, 41, 56, 62, 73, 84, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114]
# data_list = [1, 2, 3, 4, 5, 6]
data_list = [1, 3, 4, 5, 6, 7, 8, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29,
            31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 
            60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 83, 85, 86, 87]
# data_list = [2, 9, 12, 25, 30, 41, 56, 62, 73]
# data_list = [113, 114]
# data_list = [115, 116]
# data_list = [113, 114, 115, 116]
data_list = [111, 112, 113, 114, 115, 116, 117, 118]
data_list = [119, 120, 121, 122, 123]
# data_list = [
#     1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
#     31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 
#     60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
#     90, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109
# ]
# data_list = [80, 81, 82, 83, 84, 85, 86, 87, 90, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 111, 112]

total_wins = 0
total_loss = 0
main_counter = 0
win_amt = 5000
loss_amt = 77000  # 7700  27300 77000

# s_num = 20
all_balance = []

gap = 16
num_1 = 1
num_2 = 5
for x in data_list:
    # print(f"--->>> Data - {x} <<<---")
    df = pd.read_csv(f"colour_records/rec_{x}_new.csv")
    # df = pd.read_csv(f"colour_records/new_00{x}.csv")
    # print(df.shape[0])

    record_check = []
    # red_list, green_list, blue_list = [], [], []
    # color_record = (red_list, green_list, blue_list)
    start_trade = False
    start_gap = False
    start_gap_count = 0
    win_count = 0
    loss_count = 0

    trade_counter = 0
    win_check = []
    cold_nums_list = []

    forty_nine = {i: 0 for i in range(1, 50)}

    # for b1, b2, b3, b4, b5, b6 in zip(df["b1"], df["b2"], df["b3"], df["b4"], df["b5"], df["b6"]):
    for index, row in df[['b1', 'b2', 'b3', 'b4', 'b5', 'b6']].iterrows():
        draw_nums = tuple(row)
        # print(draw_nums)
        # print(b1, b2, b3, b4, b5, b6)
        main_counter += 1
        for key in forty_nine.keys():
            if key in draw_nums:
                forty_nine[key] = 0
                # print("the number -->", key)
            else:
                forty_nine[key] += 1
        # print(draw_nums)
        # print(forty_nine)

        

        # Get the highest 4 keys based on their values
        # cold_nums_dict = dict(sorted(forty_nine.items(), key=lambda item: item[1], reverse=True)[:4])
        cold_nums = sorted(forty_nine, key=forty_nine.get, reverse=True)[:num_2][-4:]
        cold_nums_list.append(cold_nums)
        # selected_nums = cold_nums
        # print(f"{cold_nums} - {draw_nums}")
        cold_nums_dict= {x:forty_nine[x] for x in cold_nums}
        # print(cold_nums)
        # print(cold_nums_dict)

        if index > 0: 
            if start_trade == False:
                if start_gap == True:
                    start_gap_count += 1
                    if all(x > gap for x in cold_nums):
                        selected_nums = cold_nums
                        # print("------------------------------------ TRADE <<<<<<<<<<<<")
                        start_trade = True

                elif len(set(cold_nums_list[-2]) & set(draw_nums)) >= num_1:
                    start_gap = True
                    # print("------------------------------------ GAP <---")
            
            else:
                trade_counter += 1
                win_check.append(any(y in draw_nums for y in selected_nums))
                selected_nums = cold_nums
                if trade_counter == 3:
                    if False in win_check:
                        # print("-"*35, f"WIN", f"{selected_nums} - {draw_nums}")
                        win_count += 1
                    else:
                        # print("-"*100, f"Loss --> {selected_nums} - {draw_nums}")
                        loss_count += 1
                    start_trade = False
                    start_gap = False
                    start_gap_count = 0
                    trade_counter = 0
                    win_check = []
                
    total_wins += win_count
    total_loss += loss_count
    # print(f"Wins - {win_count} = {win_count * win_amt}")
    # print(f"Loss - {loss_count} = {loss_count * loss_amt}")
    # print(f"---------------------------> Balance = {(win_count * win_amt) - (loss_count * loss_amt)}\n")

print(f"\nTotal Wins = {total_wins}")
print(f"Total Loss = {total_loss}")

win_amount = total_wins * win_amt
loss_amount = total_loss * loss_amt
print(f"Win Amount = {win_amount}")
print(f"Loss Amount = {loss_amount}")
print(f"\nBALANCE = {win_amount - loss_amount} <---------------------")
print(f"\nTotal Draws = {main_counter} --> {round((main_counter * 50) / 60)} minutes --> {round(((main_counter * 50) / 60) / 60)} hours\
--> {round((((main_counter * 50) / 60) / 60) / 5)} days ##########################################################################\n")

# all_balance.append((win_amount - loss_amount, s_num))

# # print(all_balance)
# df = pd.DataFrame(all_balance, columns=['balance', 's_num'])
# # temp = [bal[0] for bal in all_balance]
# # print(temp)
# # print(max(temp))
# df = df.sort_values(by='balance', ascending=False)
# df.head(10)  # 11, 10, 12

Total Wins = 200
Total Loss = 9
Win Amount = 1000000
Loss Amount = 693000

BALANCE = 307000 <---------------------

Total Draws = 4530 --> 3775 minutes --> 63 hours--> 13 days ##########################################################################

In [13]:
import pandas as pd

ball_colors = ("red", "green", "blue")

# n1, n2, n3, n4, n5, n6, n7, n8, n9, n10 = map(int, "4104254446")  # 22432  32231

# data_list = [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
# data_list = [110, 111]
# data_list = [2, 9, 12, 25, 30, 41, 56, 62, 73, 84, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114]
# data_list = [1, 2, 3, 4, 5, 6]
data_list = [1, 3, 4, 5, 6, 7, 8, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29,
            31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 
            60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 83, 85, 86, 87]
# data_list = [2, 9, 12, 25, 30, 41, 56, 62, 73]
# data_list = [113, 114]
# data_list = [115, 116]
# data_list = [113, 114, 115, 116]
# data_list = [111, 112, 113, 114, 115, 116, 117, 118]
# data_list = [119, 120, 121, 122]
# data_list = [
#     1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
#     31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 
#     60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
#     90, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109
# ]
# data_list = [80, 81, 82, 83, 84, 85, 86, 87, 90, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 111, 112]


win_amt = 5000
loss_amt = 77000  # 7700  27300 77000

# s_num = 20
all_balance = []
for num_1 in range(10, 21):
    print("Loop -->", num_1)
    for s_num in range(3, 21):
        if num_1 >= s_num:
            for num_2 in range(21):
                if s_num >=  num_2:
                    total_wins = 0
                    total_loss = 0
                    main_counter = 0
                    for x in data_list:
                        # print(f"--->>> Data - {x} <<<---")
                        df = pd.read_csv(f"colour_records/rec_{x}_new.csv")
                        # df = pd.read_csv(f"colour_records/new_00{x}.csv")
                        # print(df.shape[0])

                        record_check = []
                        # red_list, green_list, blue_list = [], [], []
                        # color_record = (red_list, green_list, blue_list)
                        start_trade = False
                        win_count = 0
                        loss_count = 0

                        trade_counter = 0
                        win_check = []

                        forty_nine = {i: 0 for i in range(1, 50)}

                        # for b1, b2, b3, b4, b5, b6 in zip(df["b1"], df["b2"], df["b3"], df["b4"], df["b5"], df["b6"]):
                        for index, row in df[['b1', 'b2', 'b3', 'b4', 'b5', 'b6']].iterrows():
                            draw_nums = tuple(row)
                            # print(draw_nums)
                            # print(b1, b2, b3, b4, b5, b6)
                            main_counter += 1
                            for key in forty_nine.keys():
                                if key in draw_nums:
                                    forty_nine[key] = 0
                                    # print("the number -->", key)
                                else:
                                    forty_nine[key] += 1
                            # print(draw_nums)
                            # print(forty_nine)

                            if index > 0:
                                record_check.append(any(y in draw_nums for y in cold_nums))

                            # Get the highest 4 keys based on their values
                            # cold_nums_dict = dict(sorted(forty_nine.items(), key=lambda item: item[1], reverse=True)[:4])
                            cold_nums = sorted(forty_nine, key=forty_nine.get, reverse=True)[:4][-4:]
                            # selected_nums = cold_nums
                            cold_nums_dict= {x:forty_nine[x] for x in cold_nums}
                            # print(cold_nums)
                            # print(cold_nums_dict)

                            if index >= num_1:
                                
                                if start_trade == False:
                                    # if all(i in range(s_num+1, s_num+11) for i in cold_nums_dict.values()):
                                    if record_check[-s_num:].count(True) == num_2:
                                        selected_nums = cold_nums
                                        # print(f"{selected_nums} - {draw_nums}")
                                        start_trade = True
                                else:
                                    trade_counter += 1
                                    # if any(y in draw_nums for y in selected_nums):
                                    win_check.append(any(y in draw_nums for y in selected_nums))
                                    selected_nums = cold_nums
                                    if trade_counter == 3:
                                        if False in win_check:
                                            # print("-"*35, f"WIN", f"{selected_nums} - {draw_nums}")
                                            win_count += 1
                                        else:
                                            # print("-"*100, f"Loss --> {selected_nums} - {draw_nums}")
                                            loss_count += 1
                                        start_trade = False
                                        trade_counter = 0
                                        win_check = []
                                        
                        total_wins += win_count
                        total_loss += loss_count
                        # print(f"Wins - {win_count} = {win_count * win_amt}")
                        # print(f"Loss - {loss_count} = {loss_count * loss_amt}")
                        # print(f"---------------------------> Balance = {(win_count * win_amt) - (loss_count * loss_amt)}\n")

                    # print(f"\nTotal Wins = {total_wins}")
                    # print(f"Total Loss = {total_loss}")

                    win_amount = total_wins * win_amt
                    loss_amount = total_loss * loss_amt
                    # print(f"Win Amount = {win_amount}")
                    # print(f"Loss Amount = {loss_amount}")
                    # print(f"\nBALANCE = {win_amount - loss_amount} <---------------------")
                    # print(f"\nTotal Draws = {main_counter} --> {round((main_counter * 50) / 60)} minutes --> {round(((main_counter * 50) / 60) / 60)} hours\
                    # --> {round((((main_counter * 50) / 60) / 60) / 5)} days ##########################################################################\n")

                    all_balance.append((win_amount - loss_amount, num_1, s_num, num_2))

# print(all_balance)
df = pd.DataFrame(all_balance, columns=['balance', 'num_1', 's_num', 'num_2'])
# temp = [bal[0] for bal in all_balance]
# print(temp)
# print(max(temp))
df = df.sort_values(by='balance', ascending=False)
df.head(20)  # 11, 10, 12

Loop --> 10
Loop --> 11
Loop --> 12
Loop --> 13
Loop --> 14
Loop --> 15
Loop --> 16
Loop --> 17
Loop --> 18
Loop --> 19
Loop --> 20

      balance  num_1  s_num  num_2
97     338000     11      8      7
555    338000     15     15     11
37     338000     10      8      7
685    333000     16     15     11
169    333000     12      8      7
1181   328000     19     15     11
597    328000     16      8      7
254    328000     13      8      7
353    328000     14      8      7
467    328000     15      8      7
997    328000     18     15     11
832    328000     17     15     11
744    323000     17      8      7
1385   323000     20     15     11
1093   323000     19      8      7
1297   323000     20      8      7
909    323000     18      8      7
129    272000     11     11      9
201    272000     12     11      9
286    267000     13     11      9

In [14]:
data = [
    [338000, 11, 8, 7],
    [338000, 15, 15, 11],
    [338000, 10, 8, 7],
    [333000, 16, 15, 11],
    [333000, 12, 8, 7],
    [328000, 19, 15, 11],
    [328000, 16, 8, 7],
    [328000, 13, 8, 7],
    [328000, 14, 8, 7],
    [328000, 15, 8, 7],
    [328000, 18, 15, 11],
    [328000, 17, 15, 11],
    [323000, 17, 8, 7],
    [323000, 20, 15, 11],
    [323000, 19, 8, 7],
    [323000, 20, 8, 7],
    [323000, 18, 8, 7],
    [272000, 11, 11, 9],
    [272000, 12, 11, 9],
    [267000, 13, 11, 9]
]

# Extract the last three columns from the data
last_three_cols = [row[-3:] for row in data]

# Calculate the sum of each column
sum_columns = [sum(col) for col in zip(*last_three_cols)]

# Calculate the average
num_rows = len(data)
average_columns = [sum_val / num_rows for sum_val in sum_columns]

print(average_columns)

[15.3, 10.55, 8.5]

In [11]:
df.head(50)

      balance  num_1  s_num  num_2
1064   170100     19      4      4
225    167000     13      4      4
568    164700     16      4      4
140    164300     12      4      4
880    162400     18      4      4
68     161600     11      4      4
8      161600     10      4      4
1268   160100     20      4      4
715    154700     17      4      4
438    152000     15      4      4
324    152000     14      4      4
1436   140600     20     18     11
1232   125200     19     18     11
865    118100     17     17     11
1252   117400     19     19     12
1214   115800     19     17     11
1456   107400     20     19     12
1418   105800     20     17     11
1048   102100     18     18     11
1030    95400     18     17     11
1143    84200     19     13      2
517     83800     15     13      2
794     81500     17     13      2
1347    79200     20     13      2
81      74700     11      6      6
153     74700     12      6      6
21      74700     10      6      6
238     74700     13      6      6
647     73800     16     13      2
581     69700     16      6      6
728     69700     17      6      6
337     69700     14      6      6
1077    69700     19      6      6
893     69700     18      6      6
451     69700     15      6      6
1281    69700     20      6      6
959     68800     18     13      2
304     68400     13     13      2
403     68400     14     13      2
1476    64900     20     20     12
1114    63000     19     10      9
275     63000     13     10      9
58      63000     10     10      9
488     63000     15     10      9
118     63000     11     10      9
618     63000     16     10      9
1318    63000     20     10      9
930     63000     18     10      9
765     63000     17     10      9
190     63000     12     10      9

In [12]:
# df3 = df.copy()
df3.head(50)

      balance  num_1  s_num  num_2
1064   170100     19      4      4
225    167000     13      4      4
568    164700     16      4      4
140    164300     12      4      4
880    162400     18      4      4
68     161600     11      4      4
8      161600     10      4      4
1268   160100     20      4      4
715    154700     17      4      4
438    152000     15      4      4
324    152000     14      4      4
1436   140600     20     18     11
1232   125200     19     18     11
865    118100     17     17     11
1252   117400     19     19     12
1214   115800     19     17     11
1456   107400     20     19     12
1418   105800     20     17     11
1048   102100     18     18     11
1030    95400     18     17     11
1143    84200     19     13      2
517     83800     15     13      2
794     81500     17     13      2
1347    79200     20     13      2
81      74700     11      6      6
153     74700     12      6      6
21      74700     10      6      6
238     74700     13      6      6
647     73800     16     13      2
581     69700     16      6      6
728     69700     17      6      6
337     69700     14      6      6
1077    69700     19      6      6
893     69700     18      6      6
451     69700     15      6      6
1281    69700     20      6      6
959     68800     18     13      2
304     68400     13     13      2
403     68400     14     13      2
1476    64900     20     20     12
1114    63000     19     10      9
275     63000     13     10      9
58      63000     10     10      9
488     63000     15     10      9
118     63000     11     10      9
618     63000     16     10      9
1318    63000     20     10      9
930     63000     18     10      9
765     63000     17     10      9
190     63000     12     10      9

In [8]:
# df1 = df.copy()
df1.head(50)

      balance  num_1  s_num  num_2
919    179800     17      9      5
344    158200     12      9      5
3245   156400     26     15      3
4017   154100     28     15      3
642    154000     15      9      5
1084   152100     18      9      5
845    150600     16     15      3
4905   149100     30     15      3
4446   149100     29     15      3
772    149000     16      9      5
2900   148700     25     15      3
715    147900     15     15      3
1482   145000     20     10      5
1268   144800     19      9      5
1472   144800     20      9      5
5395   144100     31     15      3
1094   141900     18     10      5
2581   141000     24     15      3
5553   140700     31     23      5
272    140100     11      9      5
9529   140000     37     34     15
5322   139100     31      9      5
7518   138900     34     33     19
8802   138900     36     33     19
6929   138900     33     33     19
8142   138900     35     33     19
4373   138700     29      9      5
528    138600     14      9      5
7219   138400     34     23      5
8503   138400     36     23      5
9200   138400     37     23      5
7843   138400     35     23      5
3944   138300     28      9      5
3544   138300     27      9      5
1697   137500     21      9      5
8903   137200     36     36     15
7061   136800     34     15      3
6472   136800     33     15      3
8553   136400     36     25      6
7893   136400     35     25      6
9250   136400     37     25      6
7269   136400     34     25      6
1545   135600     20     15      3
1770   135600     21     15      3
1341   135600     19     15      3
429    135500     13      9      5
1962   134800     22     11      2
8172   134600     35     34     15
6988   134500     34      9      5
5844   134100     32      9      5

In [7]:
# df2 = df.copy()
df2.head(50)

      balance  num_1  s_num  num_2
282    356400     11     10      5
222    356400     10     10      5
3954   347600     28     10      5
439    346400     13     10      5
5332   345300     31     10      5
4383   342600     29     10      5
5854   340300     32     10      5
3554   339900     27     10      5
3182   339900     26     10      5
354    338700     12     10      5
6998   338000     34     10      5
4842   337600     30     10      5
2837   337200     25     10      5
538    336400     14     10      5
652    336400     15     10      5
929    331400     17     10      5
782    331400     16     10      5
6409   327600     33     10      5
2224   321800     23     10      5
2518   321800     24     10      5
1954   319100     22     10      5
1482   316400     20     10      5
1094   313700     18     10      5
1707   311400     21     10      5
1278   308700     19     10      5
4135   273200     28     21     10
3735   270500     27     21     10
3363   270500     26     21     10
5513   263200     31     21     10
6035   263200     32     21     10
4564   260500     29     21     10
7179   258200     34     21     10
6590   258200     33     21     10
5023   255500     30     21     10
3018   255100     25     21     10
2699   255100     24     21     10
2405   255100     23     21     10
2135   252400     22     21     10
1888   244700     21     21     10
4348   227700     29      6      4
6963   220800     34      6      4
5297   220400     31      6      4
3919   220000     28      6      4
99     218800      8      6      4
47     218800      6      6      4
69     218800      7      6      4
4807   217700     30      6      4
145    210600      9      7      4
5819   210400     32      6      4
894    209200     17      6      4

In [3]:
import itertools
import pandas as pd


all_balance = []

# Generate all possible combinations of five digits ranging from 0 to 4
combinations = itertools.product(range(5), repeat=5)  # repeat=10 for 10 numbers
all_combinations = []

# Convert each combination to a string and print
for combination in combinations:
    password = ''.join(map(str, combination))
    all_combinations.append(password)
    # print(password)
print("Total Combinations =", len(all_combinations))

counter = 1
checkpoint = 500
for combo in all_combinations:
    n1, n2, n3, n4, n5 = map(int, combo)
    all_balance.append(best_combo(n1, n2, n3, n4, n5))
    if counter == checkpoint:
        print(f"Counter is at {counter}")
        checkpoint += 500
    counter += 1
    # print(n1, n2, n3, n4, n5)

# save the data -----------------
temp_dict = {
    "combination": [f"({x[-1]})" for x in all_balance],
    "t_won": [x[0] for x in all_balance],
    "t_lost": [x[1] for x in all_balance],
    "balance": [x[2] for x in all_balance]
    # "all": all_balance
}
combination_data = pd.DataFrame(temp_dict)
# combination_data = combination_data.sort_values(by='balance', ascending=False, ignore_index=True)
combination_data.to_csv('number_data/five_1_to_110.csv', index=False)
combination_data.head(10)

# takes approx 1100 minutes

Total Combinations = 3125
Counter is at 500
Counter is at 1000
Counter is at 1500
Counter is at 2000
Counter is at 2500
Counter is at 3000

  combination  t_won  t_lost  balance
0     (00000)   9344     414 -7100000
1     (00001)   9342     416 -7370000
2     (00002)   9380     378 -2240000
3     (00003)   8889     383 -5345000
4     (00004)   5182     232 -4250000
5     (00010)   9331     427 -8855000
6     (00011)   9332     425 -8590000
7     (00012)   9310     415 -7400000
8     (00013)   8734     378 -5470000
9     (00014)   5022     233 -5180000

In [1]:
import pandas as pd

def best_combo(n1, n2, n3, n4, n5, n6, n7, n8, n9, n10):

    data_list = [1, 3, 4, 5, 6, 7, 8, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29,
                31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 
                60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 83, 85, 86, 87]
    
    # data_list = [100, 101, 102, 103, 104, 105, 106, 107, 108, 2, 9, 12, 25, 30, 41, 56, 62, 73, 84]
    total_wins = 0
    total_loss = 0
    main_counter = 0

    for x in data_list:
        df = pd.read_csv(f"colour_records/rec_{x}_new.csv")

        record_check = []
        red_list, green_list, blue_list = [], [], []
        color_record = (red_list, green_list, blue_list)
        start_trade = False
        win_count = 0
        loss_count = 0

        counter = 0
        temp_check = []

        for colours in df["colours"]:
            main_counter += 1
            numbers = [int(num) for num in (str(colours))]

            if len(numbers) == 1:
                numbers.insert(0, 0)
                numbers.insert(0, 0)
        
            elif len(numbers) == 2:
                numbers.insert(0, 0)
            record_check.append(numbers)

            red_list.append(numbers[0]), green_list.append(numbers[1]), blue_list.append(numbers[2])
            if len(record_check) >= 10:
                if start_trade == False:
                    count = 0
                    for color in color_record:
                        if (color[-1] >= n1) and (color[-2] >= n2) and (color[-3] >= n3) and (color[-4] >= n4) and (color[-5] >= n5) \
                        and (color[-6] >= n6) and (color[-7] >= n7) and (color[-8] >= n8) and (color[-9] >= n9) and (color[-10] >= n10):
                            start_trade = True
                            break
                        count += 1
                else:
                    counter += 1 
                    temp_check.append(color_record[count][-1])
                    if counter == 3:
                        if any(x >= 2 for x in temp_check):
                            win_count += 1
                        else:
                            loss_count += 1
                        start_trade = False
                        counter = 0
                        temp_check = []
                        
        total_wins += win_count
        total_loss += loss_count

    win_amount = total_wins * 5000
    loss_amount = total_loss * 130000
    total_balance = win_amount - loss_amount
    # print(f"\nBALANCE = {total_balance} <---")
    
    return (total_wins, total_loss, total_balance, (f"{n1}{n2}{n3}{n4}{n5}{n6}{n7}{n8}{n9}{n10}"))

In [30]:
import itertools
import pandas as pd


all_balance = []

# Generate all possible combinations of five digits ranging from 0 to 4
combinations = itertools.product(range(5), repeat=10)
all_combinations = []

# Convert each combination to a string and print
for combination in combinations:
    password = ''.join(map(str, combination))
    all_combinations.append(password)
    # print(password)
section = round(len(all_combinations) / 36)
print("Total Combinations =", len(all_combinations))
print("each section of the combination =", section, "\n")

counter = 1
checkpoint = 10000
# for combo in all_combinations[788993:section*3]:
# for combo in all_combinations[section*3:section*4]:
for combo in all_combinations[section*4:section*5]:
# for combo in all_combinations[section*5:section*6]:
# for combo in all_combinations[section*6:section*7]:
    n1, n2, n3, n4, n5, n6, n7, n8, n9, n10 = map(int, combo)
    all_balance.append(best_combo(n1, n2, n3, n4, n5, n6, n7, n8, n9, n10))
    if counter == checkpoint:
        print(f"Counter is at {counter}")
        checkpoint += 10000
    counter += 1
    # print(n1, n2, n3, n4, n5, n6, n7, n8, n9, n10)

# save the data -----------------
temp_dict = {
    "combination": [f"({x[-1]})" for x in all_balance],
    "t_won": [x[0] for x in all_balance],
    "t_lost": [x[1] for x in all_balance],
    "balance": [x[2] for x in all_balance]
    # "all": all_balance
}
combination_data = pd.DataFrame(temp_dict)
# combination_data = combination_data.sort_values(by='balance', ascending=False, ignore_index=True)
combination_data.to_csv('number_data/nums_6.csv', index=False)
combination_data.head(10)

# takes approx 1100 minutes

Total Combinations = 9765625
each section of the combination = 271267

Counter is at 10000
Counter is at 20000
Counter is at 30000
Counter is at 40000
Counter is at 50000
Counter is at 60000
Counter is at 70000
Counter is at 80000
Counter is at 90000
Counter is at 100000
Counter is at 110000
Counter is at 120000
Counter is at 130000
Counter is at 140000
Counter is at 150000
Counter is at 160000
Counter is at 170000
Counter is at 180000
Counter is at 190000
Counter is at 200000
Counter is at 210000
Counter is at 220000
Counter is at 230000
Counter is at 240000
Counter is at 250000
Counter is at 260000
Counter is at 270000

    combination  t_won  t_lost  balance
0  (0234210233)     43       4  -305000
1  (0234210234)     11       1   -75000
2  (0234210240)     35       0   175000
3  (0234210241)     34       0   170000
4  (0234210242)     20       0   100000
5  (0234210243)     10       0    50000
6  (0234210244)      3       0    15000
7  (0234210300)    200      18 -1340000
8  (0234210301)    182      16 -1170000
9  (0234210302)    131      12  -905000

In [16]:
# save the data -----------------
temp_dict = {
    "combination": [f"({x[-1]})" for x in all_balance],
    "t_won": [x[0] for x in all_balance],
    "t_lost": [x[1] for x in all_balance],
    "balance": [x[2] for x in all_balance]
    # "all": all_balance
}

combination_data = pd.DataFrame(temp_dict)
# combination_data = combination_data.sort_values(by='balance', ascending=False, ignore_index=True)
combination_data.to_csv('number_data/nums_6.csv', index=False)
combination_data.head(10)

    combination  t_won  t_lost  balance
0  (0142200020)   1489      41  2115000
1  (0142222020)    613       8  2025000
2  (0142222021)    576       7  1970000
3  (0142201020)   1368      38  1900000
4  (0142200120)   1390      39  1880000
5  (0142222121)    530       6  1870000
6  (0142200021)   1387      39  1865000
7  (0142222120)    567       8  1795000
8  (0142200121)   1292      36  1780000
9  (0142221020)    910      22  1690000

In [23]:
print(pd.read_csv("number_data/nums_1.csv").shape[0])
print(pd.read_csv("number_data/nums_2.csv").shape[0])
print(pd.read_csv("number_data/nums_3.csv").shape[0])

496182
46351
246459

In [24]:
496182 + 46351 + 246459

788992

In [25]:
combination_data.tail(5)

         combination  t_won  t_lost   balance
246449  (0200021001)   6780     341 -10430000
246450  (0200001012)   6753     340 -10435000
246451  (0200120100)   6766     342 -10630000
246452  (0120110101)   6858     346 -10690000
246453  (0120002000)   6862     347 -10800000
246454  (0200011102)   6595     337 -10835000
246455  (0200001102)   6734     344 -11050000
246456  (0200001002)   6852     352 -11500000
246457  (0200101012)   6664     346 -11660000
246458  (0200002002)   6380     336 -11780000

In [58]:
len(all_combinations)

9765625

In [59]:
len(all_balance)

496182

In [14]:
496183 + 46353

542536

In [60]:
# Sort the data based on total_balance in descending order and total_loss in ascending order
sorted_data = sorted(enumerate(all_balance), key=lambda x: (-x[1][2], x[1][1]))

# Get the index position of the tuple with the max total_balance and least total_loss
max_balance_least_loss_index = sorted_data[0][0]

print(max_balance_least_loss_index)
print(all_balance[max_balance_least_loss_index])

351511
(629, 10, 1845000, '0042222021')

In [61]:
# Sort the data based on total_balance in descending order and total_loss in ascending order
sorted_data = sorted(all_balance, key=lambda x: (-x[2], x[1]))

# Get the tuple with the max total_balance and least total_loss
max_balance_least_loss = sorted_data[:50]

# max_balance_least_loss
"40341", "22433", "32432", "41142", "40042", "02424", "40124", "12414", "11424", "40214", "02414"  # 3
"41242", "40143", "22442", "41143", "41342", "40342", "13442"  # 1
for val in max_balance_least_loss:
    print(f"{round((val[0] / val[1]), 2)} ---> {val}")

62.9 ---> (629, 10, 1845000, '0042222021')
56.17 ---> (674, 12, 1810000, '0042222020')
64.44 ---> (580, 9, 1730000, '0042222121')
27.44 ---> (6531, 238, 1715000, '0101030000')
32.31 ---> (1648, 51, 1610000, '0010003303')
32.81 ---> (1542, 47, 1600000, '0110003303')
29.17 ---> (2946, 101, 1600000, '0004021000')
40.27 ---> (886, 22, 1570000, '0102232231')
52.08 ---> (625, 12, 1565000, '0042222120')
33.54 ---> (1375, 41, 1545000, '0110310400')
40.57 ---> (852, 21, 1530000, '0111120403')
32.8 ---> (1476, 45, 1530000, '0110300400')
51.33 ---> (616, 12, 1520000, '0111022403')
44.94 ---> (719, 16, 1515000, '0042112030')
35.74 ---> (1108, 31, 1510000, '0102300400')
32.4 ---> (1523, 47, 1505000, '0011003303')
39.55 ---> (870, 22, 1490000, '0042222011')
31.96 ---> (1598, 50, 1490000, '0042200020')
55.7 ---> (557, 10, 1485000, '0110211342')
50.75 ---> (609, 12, 1485000, '0100211342')
47.14 ---> (660, 14, 1480000, '0100210342')
32.88 ---> (1414, 43, 1480000, '0111003303')
47.07 ---> (659, 14, 1475000, '0042112130')
37.8 ---> (945, 25, 1475000, '0042222010')
37.76 ---> (944, 25, 1470000, '0102232230')
33.71 ---> (1281, 38, 1465000, '0110301401')
32.37 ---> (1489, 46, 1465000, '0042200021')
50.25 ---> (603, 12, 1455000, '0110210342')
33.61 ---> (1277, 38, 1445000, '0111310400')
32.88 ---> (1381, 42, 1445000, '0110300401')
34.0 ---> (1224, 36, 1440000, '0101232231')
41.11 ---> (781, 19, 1435000, '0042102030')
46.36 ---> (649, 14, 1425000, '0111220403')
33.47 ---> (1272, 38, 1420000, '0110311400')
32.76 ---> (1376, 42, 1420000, '0111300400')
40.89 ---> (777, 19, 1415000, '0042012030')
34.84 ---> (1115, 32, 1415000, '0012000403')
28.92 ---> (2805, 97, 1415000, '0004121000')
28.94 ---> (2778, 96, 1410000, '0104021000')
32.69 ---> (1373, 42, 1405000, '0110301400')
29.04 ---> (2672, 92, 1400000, '0110240100')
42.41 ---> (721, 17, 1395000, '0042102031')
56.78 ---> (511, 9, 1385000, '0042202031')
44.47 ---> (667, 15, 1385000, '0011022403')
42.29 ---> (719, 17, 1385000, '0042102130')
35.55 ---> (1031, 29, 1385000, '0102301400')
28.89 ---> (2773, 96, 1385000, '0004021010')
37.04 ---> (926, 25, 1380000, '0111020403')
37.96 ---> (873, 23, 1375000, '0111021403')
44.27 ---> (664, 15, 1370000, '0042102131')

In [53]:
# Sort the data based on total_balance in descending order
sorted_data = sorted(all_balance, key=lambda x: x[2], reverse=True)

# Get the tuple with the highest total_balance
highest_total_balance_tuple = sorted_data[:20]

highest_total_balance_tuple

[(516, 11, 1150000, (2, 2, 4, 3, 2)),
 (2378, 83, 1100000, (3, 2, 2, 3, 1)),
 (812, 23, 1070000, (0, 2, 4, 3, 2)),
 (344, 5, 1070000, (4, 1, 0, 4, 2)),
 (369, 6, 1065000, (4, 0, 0, 4, 2)),
 (749, 21, 1015000, (1, 2, 4, 3, 2)),
 (2563, 91, 985000, (3, 2, 2, 3, 0)),
 (308, 5, 890000, (4, 1, 1, 4, 2)),
 (333, 6, 885000, (4, 0, 1, 4, 2)),
 (3475, 127, 865000, (3, 1, 2, 3, 0)),
 (476, 12, 820000, (4, 0, 1, 1, 4)),
 (1227, 41, 805000, (0, 1, 4, 2, 3)),
 (234, 3, 780000, (2, 3, 4, 3, 2)),
 (227, 3, 745000, (1, 2, 4, 2, 4)),
 (330, 7, 740000, (1, 2, 4, 1, 4)),
 (324, 7, 710000, (1, 1, 4, 2, 4)),
 (7730, 292, 690000, (2, 1, 2, 0, 1)),
 (242, 4, 690000, (2, 2, 4, 3, 3)),
 (892, 29, 690000, (3, 0, 4, 2, 2)),
 (265, 5, 675000, (3, 2, 4, 3, 2))]

In [109]:
max(all_balance)

820000

In [100]:
all_balance.index(555000)

42

In [101]:
all_combinations[42]

'52100'

In [110]:
new_balance = sorted(all_balance)
new_balance[-1]

820000

In [111]:
new_balance[-10:]

[445000,
 465000,
 470000,
 475000,
 505000,
 515000,
 550000,
 590000,
 695000,
 820000]

In [77]:
print(len(all_combinations[:(len(all_balance))]))
len(all_balance)
all_balance[2]

496182

(7151, 333, -7535000, '0000000002')

In [78]:
temp_dict = {
    "combination": all_combinations[:(len(all_balance))],
    "balance": all_balance
}

combination_data = pd.DataFrame(temp_dict)
combination_data = combination_data.sort_values(by='balance', ascending=False, ignore_index=True)
combination_data.to_csv('balance_combi4.csv', index=False)
combination_data.head(10)

  combination                            balance
0  0000200000  (7193, 291, -1865000, 0000200000)
1  0000020000  (7188, 296, -2540000, 0000020000)
2  0000000020  (7181, 303, -3485000, 0000000020)
3  0000110010  (7179, 300, -3105000, 0000110010)
4  0100010000  (7178, 306, -3890000, 0100010000)
5  0100000010  (7178, 306, -3890000, 0100000010)
6  0100010100  (7178, 298, -2850000, 0100010100)
7  0100000100  (7176, 308, -4160000, 0100000100)
8  0011100000  (7176, 299, -2990000, 0011100000)
9  0100000011  (7175, 305, -3775000, 0100000011)

In [ ]:
list(combination_data["balance"].head(100).values)

In [186]:
"66666" in all_combinations

True

In [187]:
all_combinations[-6:]

['66661', '66662', '66663', '66664', '66665', '66666']

In [188]:
len(all_combinations)

16807

In [6]:
import math
import pandas as pd

red_list = list(range(1, 49))[0:49:3]
blue_list = list(range(1, 49))[1:49:3]
green_list = list(range(1, 49))[2:49:3]
colour_list = (red_list, green_list, blue_list)
# print(red_list)
# print(blue_list)
# print(green_list)

all_draws = 0
all_played = 0
total_win = 0
all_loss = 0

max_martingale_level = 1
colours = ("red", "green", "blue")

data_list = [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
             41, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]

for x in data_list:
    # print(f"--->>> Data - {x} <<<---")
    df = pd.read_csv(f"colour_records/rec_{x}_new.csv")

    counter = 0
    stake_count = 0
    start_trade = False
    # skip_trade = False
    win_count = 0
    loss_count = 0
    trade_colour = None
    loss_count_list = []
    total_loss = 0

    # for b1, b2, b3, b4, b5, b6 in zip(df["b1"], df["b2"], df["b3"], df["b4"], df["b5"], df["b6"]):
    for ball_6, color in zip(df["b6"], df["colours"]):
        counter += 1
        numbers = [int(num) for num in (str(color))]

        if len(numbers) == 1:
            numbers.insert(0, 0)
            numbers.insert(0, 0)
    
        if len(numbers) == 2:
            numbers.insert(0, 0)
        if len(numbers) == 3:
            if start_trade:
                trade_colour = numbers[colour_index]
                if numbers[colour_index] >= 2:
                    loss_count_list.append(loss_count)
                    win_count += 1
                    loss_count = 0
                    start_trade = False
                    # print(f"WIN = {win_count} --> {numbers} --> {colours[colour_index]} = {trade_colour}\n")
                else:
                    loss_count += 1
                    if loss_count >= max_martingale_level:
                        total_loss += 1
                        loss_count = 0
                        start_trade = False
                        # print(f"lOSS = {loss_count} --> {numbers} --> {colours[colour_index]} = {trade_colour}\n")
                    
            # for i, c_list in enumerate(colour_list):
            #     if ball_6 in c_list:
            #         colour_index = i
            #         # print(ball_6, colours[colour_index], c_list)
            #         break
            num = 3
            if num in numbers and (numbers.count(num) == 1):
                # print(numbers)
                colour_index = numbers.index(num)
                other_index = [0, 1, 2]
                other_index.remove(colour_index)
                if ((numbers[other_index[0]] == 2) or numbers[other_index[1]] == 2):
                    stake_count += 1
                    trade_colour = colours[colour_index]
                    start_trade = True
                    # print(f"{ball_6} - {numbers} --> {trade_colour}")

    if start_trade and loss_count >= (max_martingale_level - 1):
        total_loss += 1
    # print(f"Total Draws = {counter}")
    # print(f"TOTAL WINS = {win_count}")
    # print(f"Total Lost = {total_loss}")
    # total_minutes = (counter * 50) // 60
    # print(f"Time Taken = {total_minutes // 60}hrs {total_minutes % 60}mins ----------------------------------------------->>>>>>>>>>>>>\n")
        
    all_draws += counter  
    all_played += stake_count          
    total_win += win_count
    all_loss += total_loss

target = 1000
print(f"\nProfit Target = {target}")
odd = 1.5
martingale_levels = max_martingale_level
martingale_loss = 0
martingale_stakes = []
for x in range(martingale_levels):
    stake = math.ceil((target + martingale_loss) / (odd - 1))
    martingale_stakes.append(stake)
    martingale_loss += stake
print(f"Martingale Levels - {martingale_stakes}")
max_loss = sum(martingale_stakes)
print(f"Max Loss Amount = {max_loss}")
# -------------------------------------------------------

print(f"\nALL TOTAL DRAWS = {all_draws}")
print(f"TOTAL WINS = {total_win}")
print(f"TOTAL LOSSES = {all_loss}")
print(f"Total Profit = {(total_win * target) - (all_loss * max_loss)}")

Profit Target = 1000
Martingale Levels - [2000]
Max Loss Amount = 2000

ALL TOTAL DRAWS = 14789
TOTAL WINS = 4760
TOTAL LOSSES = 2602
Total Profit = -444000

In [94]:
df.head()

,b1,b2,b3,b4,b5,b6,none_T100,green_T100,red_T100,blue_T100,none_LD,green_LD,red_LD,blue_LD,colours,total
0,46,28,22,13,40,4,24,25,25,26,5,6,0,2,600,153
1,32,22,48,39,28,42,24,26,24,26,6,0,1,3,231,211
2,2,18,16,26,45,43,25,26,23,26,0,1,2,4,222,150
3,3,7,29,2,39,37,26,26,23,25,0,2,3,5,222,117
4,29,10,5,23,17,32,26,26,22,26,1,3,4,0,105,116

# Best strategy so far ------------------------------------------------------

In [204]:
import math
import pandas as pd

total_win = 0
all_loss = 0
all_draws = 0
max_martingale_level = 12

# data_list = [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
#              31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]

data_list = [43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]
for x in data_list:
    # print(f"--->>> Data - {x} <<<---")
    df = pd.read_csv(f"colour_records/rec_{x}_new.csv")

    start_trade = False
    max_num = 12
    min_num = 6
    # last_draw_num = 13
    green_count, red_count, blue_count = [], [], []
    colour_list = [green_count, red_count, blue_count]
    green_last_draw, red_last_draw, blue_last_draw = [], [], []
    last_draw_list = [green_last_draw, red_last_draw, blue_last_draw]
    min_colour_list = []
    counter = 0
    win_count = 0
    loss_count_list = []
    loss_count = 0
    
    total_loss = 0

    for none, green, red, blue, green_ld, red_ld, blue_ld\
        in zip(df["none_T100"], df["green_T100"], df["red_T100"], df["blue_T100"], df["green_LD"], df["red_LD"], df["blue_LD"]):
        counter += 1
        trade_status = ""
        green_count.append(green), red_count.append(red), blue_count.append(blue)
        green_last_draw.append(green_ld), red_last_draw.append(red_ld), blue_last_draw.append(blue_ld)
        
        temp = (green, red, blue)
        if temp.count(min(temp)) == 1:
            min_colour_list.append(temp.index(min(temp)))
        else:
            min_colour_list.append(None)
        temp_2 = (green_ld, red_ld, blue_ld)
        temp_3 = (none, green, red, blue)
        if start_trade == True:
            if temp_2[colour_index] == 0:
                loss_count_list.append(loss_count)
                if loss_count < max_martingale_level:
                    win_count += 1
                    # print("-------------------------------> WIN =", win_count, "Loss_levels =", loss_count_list[-1], "Max Loss =", max(loss_count_list))
                loss_count = 0
                start_trade = False
                # if win_count >= 10:
                #     break
                
            else:
                loss_count += 1
                if loss_count >= max_martingale_level:
                    total_loss += 1
                    # print(f"------------------------------->{all_loss} MAX LOSS LEVEL REACHED >>> {loss_count} <<<----------------------------*******")
                    loss_count = 0
                    start_trade = False
                    # break

        # mid_num = sorted(list(temp))[-2]
        # if (counter >= max_num) and (temp.count(mid_num) == 1) and ((mid_num - min(temp)) <= 3) and (start_trade == False) and ((max(temp) - mid_num) <= 7):
        #     colour_index = temp.index(mid_num)
        #     colour_num = temp[colour_index]
        #     if (max(colour_list[colour_index][-max_num:-2]) < colour_num) and ((last_draw_list[colour_index][-10:]).count(0) >= 3)\
        #         and ((last_draw_list[colour_index][-10:]).count(0) <= 4) and (max(last_draw_list[colour_index][-10:]) <= 6):
        #         trade_status = "--->>mid TRADE"
        #         start_trade = True
        if (counter >= max_num) and (temp.count(max(temp)) == 1) and ((max(temp) - (sorted(list(temp))[-2])) <= 3) and (start_trade == False):
            colour_index = temp.index(max(temp))
            colour_num = temp[colour_index]
            if (max(colour_list[colour_index][-max_num:-min_num]) < colour_num) and ((last_draw_list[colour_index][-10:]).count(0) >= 4)\
                and (max(last_draw_list[colour_index][-17:]) <= 5) and len(set(colour_list[colour_index][-4:])) > 1:
                #  and ((last_draw_list[colour_index][-17:]).count(0) <= 6)
                trade_status = "--->>max TRADE"
                start_trade = True
        # print(f"{none} -- {temp} ---> {temp_2} {trade_status}")

    if start_trade:
        print(f"--->>> Data - {x} <<<--- Loss {loss_count}")
    if start_trade and loss_count >= (max_martingale_level - 1):
        total_loss += 1
        # print(f"------------------------------->{all_loss} MAX LOSS LEVEL REACHED >>> {loss_count} <<<----------------------------*******")
    # print(f"Total Draws = {counter}")
    # print(f"TOTAL WINS = {win_count}")
    # print(f"Total Lost = {total_loss}")
    # total_minutes = (counter * 50) // 60
    # print(f"Time Taken = {total_minutes // 60}hrs {total_minutes % 60}mins ----------------------------------------------->>>>>>>>>>>>>\n")

    all_draws += counter            
    total_win += win_count
    all_loss += total_loss

target = 1000
print(f"\nProfit Target = {target}")
odd = 3.8
martingale_levels = max_martingale_level
martingale_loss = 0
martingale_stakes = []
for x in range(martingale_levels):
    stake = math.ceil((target + martingale_loss) / (odd - 1))
    martingale_stakes.append(stake)
    martingale_loss += stake
print(f"Martingale Levels - {martingale_stakes}")
max_loss = sum(martingale_stakes)
print(f"Max Loss Amount = {max_loss}")
# -------------------------------------------------------

print(f"\nALL TOTAL DRAWS = {all_draws}")
print(f"TOTAL WINS = {total_win}")
print(f"TOTAL LOSSES = {all_loss}")
print(f"Total Profit = {(total_win * target) - (all_loss * max_loss)}")

--->>> Data - 43 <<<--- Loss 2
--->>> Data - 48 <<<--- Loss 1
--->>> Data - 62 <<<--- Loss 0

Profit Target = 1000
Martingale Levels - [358, 486, 659, 894, 1214, 1647, 2235, 3034, 4117, 5588, 7583, 10292]
Max Loss Amount = 38107

ALL TOTAL DRAWS = 10990
TOTAL WINS = 240
TOTAL LOSSES = 2
Total Profit = 163786

# ----------------------------------------------------------------------

In [131]:
import math
import pandas as pd

total_win = 0
all_loss = 0
max_martingale_level = 12

# old data - [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
data_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
             31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
for x in data_list:
    # print(f"--->>> Data - {x} <<<---")
    df = pd.read_csv(f"colour_records/rec_{x}_new.csv")

    start_trade = False
    max_num = 12
    min_num = 6
    last_draw_num = 13
    green_count, red_count, blue_count = [], [], []
    colour_list = [green_count, red_count, blue_count]
    green_last_draw, red_last_draw, blue_last_draw = [], [], []
    last_draw_list = [green_last_draw, red_last_draw, blue_last_draw]
    min_colour_list = []
    counter = 0
    win_count = 0
    loss_count_list = []
    loss_count = 0
    
    total_loss = 0

    for none, green, red, blue, green_ld, red_ld, blue_ld\
        in zip(df["none_T100"], df["green_T100"], df["red_T100"], df["blue_T100"], df["green_LD"], df["red_LD"], df["blue_LD"]):
        counter += 1
        green_count.append(green), red_count.append(red), blue_count.append(blue)
        green_last_draw.append(green_ld), red_last_draw.append(red_ld), blue_last_draw.append(blue_ld)
        
        temp = (green, red, blue)
        if temp.count(min(temp)) == 1:
            min_colour_list.append(temp.index(min(temp)))
        else:
            min_colour_list.append(None)
        temp_2 = (green_ld, red_ld, blue_ld)
        temp_3 = (none, green, red, blue)
        if start_trade == True:
            if temp_2[colour_index] == 0:
                loss_count_list.append(loss_count)
                if loss_count < max_martingale_level:
                    win_count += 1
                    # print("-------------------------------> WIN =", win_count, "Loss_levels =", loss_count_list[-1], "Max Loss =", max(loss_count_list))
                loss_count = 0
                start_trade = False
                # if win_count >= 20:
                #     break
                
            else:
                loss_count += 1
                if loss_count >= max_martingale_level:
                    total_loss += 1
                    # print(f"------------------------------->{all_loss} MAX LOSS LEVEL REACHED >>> {loss_count} <<<----------------------------*******")
                    loss_count = 0
                    start_trade = False


        if (counter >= last_draw_num) and (temp.count(max(temp)) == 1) and ((max(temp) - (sorted(list(temp))[-2])) <= 3) and (start_trade == False) and none > 18:
            colour_index = temp.index(max(temp))
            colour_num = temp[colour_index]
            if (max(colour_list[colour_index][-max_num:-min_num]) < colour_num) and none < (colour_num + 10) and ((last_draw_list[colour_index][-last_draw_num:]).count(0) >= 5):
                # print(none, "--", green, red, blue, "--->", green_ld, red_ld, blue_ld, "--->> TRADE")
                start_trade = True
        #     elif max(colour_list[colour_index - 1][-max_num:-min_num]) > colour_num:
        #         print(none, "--", green, red, blue, "--->", green_ld, red_ld, blue_ld)
        #     else:
        #         print(none, "--", green, red, blue, "--->", green_ld, red_ld, blue_ld)
        # else:
        #     print(none, "--", green, red, blue, "--->", green_ld, red_ld, blue_ld)

    if start_trade:
        print(f"--->>> Data - {x} <<<--- Loss {loss_count}")
    if start_trade and loss_count >= (max_martingale_level - 1):
        total_loss += 1
    # print(f"Total Draws = {counter}")
    # print(f"TOTAL WINS = {win_count}")
    # print(f"Total Lost = {total_loss}")
    # total_minutes = (counter * 50) // 60
    # print(f"Time Taken = {total_minutes // 60}hrs {total_minutes % 60}mins ----------------------------------------------->>>>>>>>>>>>>\n")
                
    total_win += win_count
    all_loss += total_loss

target = 1000
print(f"\nProfit Target = {target}")
odd = 3.8
martingale_levels = max_martingale_level
martingale_loss = 0
martingale_stakes = []
for x in range(martingale_levels):
    stake = math.ceil((target + martingale_loss) / (odd - 1))
    martingale_stakes.append(stake)
    martingale_loss += stake
print(f"Martingale Levels - {martingale_stakes}")
max_loss = sum(martingale_stakes)
print(f"Max Loss Amount = {max_loss}")
# -------------------------------------------------------

print(f"\nTOTAL WINS = {total_win}")
print(f"TOTAL LOSSES = {all_loss}")
print(f"Total Profit = {(total_win * 1000) - (all_loss * max_loss)}")

--->>> Data - 2 <<<--- Loss 4
--->>> Data - 19 <<<--- Loss 0
--->>> Data - 28 <<<--- Loss 0
--->>> Data - 35 <<<--- Loss 0
--->>> Data - 37 <<<--- Loss 1
--->>> Data - 38 <<<--- Loss 4
--->>> Data - 39 <<<--- Loss 3
--->>> Data - 48 <<<--- Loss 1

Profit Target = 1000
Martingale Levels - [358, 486, 659, 894, 1214, 1647, 2235, 3034, 4117, 5588, 7583, 10292]
Max Loss Amount = 38107

TOTAL WINS = 765
TOTAL LOSSES = 11
Total Profit = 345823

## Best so Far

In [990]:
import math
import pandas as pd

total_win = 0
all_loss = 0
all_draws = 0
max_martingale_level = 12

# old data - [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
data_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
             31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]
for x in data_list:
    # print(f"--->>> Data - {x} <<<---")
    df = pd.read_csv(f"colour_records/rec_{x}_new.csv")

    start_trade = False
    max_num = 8
    min_num = 6
    last_draw_num = 13
    green_count, red_count, blue_count = [], [], []
    colour_list = [green_count, red_count, blue_count]
    green_last_draw, red_last_draw, blue_last_draw = [], [], []
    last_draw_list = [green_last_draw, red_last_draw, blue_last_draw]
    min_colour_list = []
    counter = 0
    win_count = 0
    loss_count_list = []
    loss_count = 0
    
    total_loss = 0

    for none, green, red, blue, green_ld, red_ld, blue_ld\
        in zip(df["none_T100"], df["green_T100"], df["red_T100"], df["blue_T100"], df["green_LD"], df["red_LD"], df["blue_LD"]):
        counter += 1
        trade_status = ""
        green_count.append(green), red_count.append(red), blue_count.append(blue)
        green_last_draw.append(green_ld), red_last_draw.append(red_ld), blue_last_draw.append(blue_ld)
        
        temp = (green, red, blue)
        if temp.count(min(temp)) == 1:
            min_colour_list.append(temp.index(min(temp)))
        else:
            min_colour_list.append(None)
        temp_2 = (green_ld, red_ld, blue_ld)
        temp_3 = (none, green, red, blue)
        if start_trade == True:
            if temp_2[colour_index] == 0:
                loss_count_list.append(loss_count)
                if loss_count < max_martingale_level:
                    win_count += 1
                    # print("-------------------------------> WIN =", win_count, "Loss_levels =", loss_count_list[-1], "Max Loss =", max(loss_count_list))
                loss_count = 0
                start_trade = False
                
            else:
                loss_count += 1
                if loss_count >= max_martingale_level:
                    total_loss += 1
                    # print(f"------------------------------->{all_loss} MAX LOSS LEVEL REACHED >>> {loss_count} <<<----------------------------*******")
                    loss_count = 0
                    start_trade = False

        mid_num = sorted(list(temp))[-2]
        if (counter >= last_draw_num) and (temp.count(mid_num) == 1) and ((mid_num - min(temp)) <= 3) and (start_trade == False):
            colour_index = temp.index(mid_num)
            colour_num = temp[colour_index]
            if (max(colour_list[colour_index][-max_num:-2]) < colour_num) and ((last_draw_list[colour_index][-11:]).count(0) >= 4):
                    trade_status = "--->>mid TRADE"
                    start_trade = True
        for x in range(3):
            if (counter >= last_draw_num) and (start_trade == False) and none > 18:
                colour_index = x
                colour_num = temp[colour_index]
                if (max(colour_list[colour_index][-max_num:-min_num]) < colour_num) and none < (colour_num + 10) and ((last_draw_list[colour_index][-last_draw_num:]).count(0) >= 5):
                        trade_status = "--->>max TRADE"
                        start_trade = True
                        break
        # print(f"{none} -- {temp} ---> {temp_2} {trade_status}")

    if start_trade and loss_count >= (max_martingale_level - 1):
        total_loss += 1
    # print(f"Total Draws = {counter}")
    # print(f"TOTAL WINS = {win_count}")
    # print(f"Total Lost = {total_loss}")
    # total_minutes = (counter * 50) // 60
    # print(f"Time Taken = {total_minutes // 60}hrs {total_minutes % 60}mins ----------------------------------------------->>>>>>>>>>>>>\n")

    all_draws += counter            
    total_win += win_count
    all_loss += total_loss

target = 1000
print(f"\nProfit Target = {target}")
odd = 3.8
martingale_levels = max_martingale_level
martingale_loss = 0
martingale_stakes = []
for x in range(martingale_levels):
    stake = math.ceil((target + martingale_loss) / (odd - 1))
    martingale_stakes.append(stake)
    martingale_loss += stake
print(f"Martingale Levels - {martingale_stakes}")
max_loss = sum(martingale_stakes)
print(f"Max Loss Amount = {max_loss}")
# -------------------------------------------------------

print(f"\nALL TOTAL DRAWS = {all_draws}")
print(f"TOTAL WINS = {total_win}")
print(f"TOTAL LOSSES = {all_loss}")
print(f"Total Profit = {(total_win * 1000) - (all_loss * max_loss)}")

Profit Target = 1000
Martingale Levels - [358, 486, 659, 894, 1214, 1647, 2235, 3034, 4117, 5588, 7583, 10292]
Max Loss Amount = 38107

ALL TOTAL DRAWS = 17506
TOTAL WINS = 2430
TOTAL LOSSES = 61
Total Profit = 105473

In [472]:
for i in range(3):
    print(i)

0
1
2

## Win all Colour Martingale  --> Best strategy so far

In [ ]:
import pandas as pd

none_counter = 0
none_checker = False
df = pd.read_csv("colour_records/rec_8.csv")
df.head()
for colours in df["colours"]:
    numbers = [int(num) for num in (str(colours))]
    if len(numbers) == 2:
        numbers.insert(0, 0)
    # print(numbers)
    if max(numbers) >= 3 and numbers.count(max(numbers)) == 1:
        none_counter = 0
    else:
        none_counter += 1
        if none_counter >= 1:
            print(none_counter, numbers)
            none_checker = True

In [ ]:
import math
import pandas as pd
# 8, 6, 5, 2, 1, 4, 3, 7
data_list = [8, 6, 5, 2, 1, 4, 3, 7]
for x in data_list:
    df = pd.read_csv(f"colour_records/rec_{x}.csv")

    # MARTINGALE LIST GENERATOR -------------------------------------
    target = 300
    odd = 3.8
    martingale_levels = 19
    martingale_loss = 0
    martingale_stakes = []
    for x in range(martingale_levels):
        stake = math.ceil((target + martingale_loss) / (odd - 1))
        martingale_stakes.append(stake)
        martingale_loss += stake
    # -------------------------------------------------------



    # COLOUR LAST DRAWN STATISTICS -------------------------------------------------------------
    none_counter = 0
    none_checker = False
    num = 0
    temp_loss_count = 0
    stat_list = []
    red_count, green_count, blue_count = 0, 0, 0
    for colours, green_6, red_6, blue_6 in zip(df["colours"], df["green_6"], df["red_6"], df["blue_6"]):
        numbers = [int(num) for num in (str(colours))]
        if len(numbers) == 2:
            numbers.insert(0, 0)

        if max(numbers) >= 3 and numbers.count(max(numbers)) == 1:
            win_colour_index = numbers.index(max(numbers))
            if win_colour_index == 0:
                red_count, green_count, blue_count = 0, green_count + 1, blue_count + 1
            elif win_colour_index == 1:
                red_count, green_count, blue_count = red_count + 1, 0, blue_count + 1
            elif win_colour_index == 2:
                red_count, green_count, blue_count = red_count + 1, green_count + 1, 0
            none_counter = 0
        else:
            red_count, green_count, blue_count = red_count + 1, green_count + 1, blue_count + 1
            none_counter += 1
            if none_counter >= 3:
                print(none_counter, "---->>", numbers)
                none_checker = True

        stat_list.append([red_count, green_count, blue_count])
        if none_checker:
            print(red_count, green_count, blue_count)
        if (martingale_levels + num) in [red_count, green_count, blue_count]:
            temp_loss_count += 1
            print(f"--------------------------------------->>> {green_6, red_6, blue_6}")
    print(f"--> Total Loss Count = {temp_loss_count}")
    
    # -----------------------------------------------------------------------------



    # STRATEGY VALIDATION CHECK -------------------------------------------------------
    red_list = []
    green_list = []
    blue_list = []

    counter = 1
    check = False
    mart_pass = False
    martingale_count_list = []
    for stat in stat_list:
        red, green, blue = stat[0], stat[1], stat[2]
        red_list.append(red), green_list.append(green), blue_list.append(blue)

            
    # # print(martingale_count_list)
    # if len(martingale_count_list) > 0:
    #     print(f"Max Martingale Count = {max(martingale_count_list)}")
    # else:
    #     print(f"Max Martingale Count = {len(martingale_count_list)} --> data not upto Martingale start level")
    
    print(f"Time Spent = {math.ceil((df.shape[0] * 50) / 60)} Minutes")
    print(f"Max Red = {max(red_list)} ---> Wins = {red_list.count(num)}")
    print(f"Max Green = {max(green_list)} ---> Wins = {green_list.count(num)}")
    print(f"Max Blue = {max(blue_list)} ---> Wins = {blue_list.count(num)}")
    print(f"------- Total Wins = {(red_list.count(num) + green_list.count(num) + blue_list.count(num) - temp_loss_count)} ------>>>\n")


    # STRATEGY VALIDATION CHECK -----------------------------------------------------------------------------------------

In [ ]:
played = 0
wins = 0
loss = 0
capital = 100_000
Lose_stake = capital * 0.03
win_stake = capital * 0.01
high_stake = capital * 0.05
high_stake_times = 2
profit = 0
profits = []
loss_count = 0

for colours in df["colours"]:
    numbers = [int(num) for num in (str(colours))]
    if max(numbers) >= 3 and numbers.count(max(numbers)) == 1:
        # previous_profit = profit
        wins += 1
        if loss_count == high_stake_times:
            profit += round(high_stake * 0.8)
        else:
            profit += round(win_stake * 0.8)
        loss_count = 0
        # print(previous_profit - profit)
        
    else:
        # previous_profit = profit
        loss += 1
        if loss_count == high_stake_times:
            profit -= high_stake * 3
            loss_count += 1
        else:
            profit -= Lose_stake
            loss_count += 1
        # print(previous_profit - profit)

    # print(profit, "---", wins)
    profits.append(profit)
    played += 1



print(f"\nPlayed - {played}")
print(f"Won - {wins}")
print(f"Loss - {loss}")
print(f"Profit = {round(profit)}\n")

print(f"Max_Profit = {max(profits)}")
print(f"Max_Loss = {min(profits)}")

In [ ]:
# df[["red_3p", "green_3p", "blue_3p"]]

print(max(df["red_3p"]))
print(max(df["green_3p"]))
print(max(df["blue_3p"]))

## 4+ Wins

In [ ]:
# 8, 6, 5, 2, 1, 4, 3, 7

df = pd.read_csv("colour_records/rec_7.csv")

num = 10

win_count = []
check_pass = False
martingale_counter = 0
loss_counter = 0
for red, green, blue in zip(df["red_4p"], df["green_4p"], df["blue_4p"]):
    if red >= num and green >= num and blue >= num:
        loss_counter += 1
        if check_pass == False:
            martingale_counter += 1
            # print(red, green, blue)
            check_pass = True
    else:
        if loss_counter > 0:
            # print("---> Max Martingale", red, green, blue)
            # print(f"---> Loss Count - {loss_counter}")
            win_count.append(loss_counter)
            loss_counter = 0
        check_pass = False
    

print(f"\nTotal games - {df.shape[0]}")
print(f"Total wins - {martingale_counter}")
if len(win_count) > 0:
    print(f"Max Martingale Level - {max(win_count)}")
else:
    print(f"Max Martingale Level - None")